### ISSUE TITLE
Error in Wiki (export path)

### ISSUE THREAD

**Issue by Searaphim** [RIOT-Makers/wpan-raspbian#3]
Very minor error in "Create-a-generic-Raspbian-image-with-6LoWPAN-support" step 4.2:

> export PATH=/opt/src/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64:/opt/src/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/:$PATH

If we follow the previous steps the toolchain should be in **/opt/src/rpi_wpan/tools/** instead of **/opt/src/tools/**

**Comment by smlng** [comment]
@Searaphim thank you for the hint - actually, there was another typo near by. They are fixed now, so I'll close this one.

Thx again, and good to know some people are using these guides 😄
