### ISSUE TITLE
YACC is needed so keep Bison

### ISSUE THREAD

**Issue by Josar** [RIOT-Makers/wpan-raspbian#4]
**Setup native 6LoWPAN router using Raspbian and RADVD**

After installing flex, in the tutorial, bison is removed. 
But to compile radvd yacc is used so keeping bison until radvd is compiled would be better, imho.

**Comment by smlng** [comment]
Thanks for the hint, fixed it! 

When I wrote this first, I also compile a new bison version from source, that's why the removal of the APT bison version. However, in the latest Raspbian the APT bison version works.
