### ISSUE TITLE
Dtc compilation fails

### ISSUE THREAD

**Issue by florian-popup** [RIOT-Makers/wpan-raspbian#7]
Hello, I try to follow the guide [here](https://github.com/RIOT-Makers/wpan-raspbian/wiki/Create-a-generic-Raspbian-image-with-6LoWPAN-support).

However when I try to compile the dts file, I get this error

> Error: mrf24j40ma-overlay.dts:2.2-8 syntax error
FATAL ERROR: Unable to parse input tree

Command line used (I removed the -@ which is not listed as a parameter neither reconized)

> dtc -O dtb -o mrf24j40ma.dtbo mrf24j40ma-overlay.dts

> dtc -v
Version: DTC 1.4.0

Which correspond to the second line (/plugin/;)

Any idea how to fix that ?
I use ubuntu mate on a rpi 3

Thanks

**Comment by florian-popup** [comment]
SO apparently there is different implementation for the same version of dtc
[here](https://github.com/beagleboard/bb.org-overlays/issues/6)

I resolved it by using [this script](https://github.com/beagleboard/bb.org-overlays/blob/master/dtc-overlay.sh)

You need to use the -@ option indeed

**Comment by smlng** [comment]
@florian-popup I just tried to compile the script on Raspbian (Jessie-lite) and didn't saw the error.

```
$ dtc -v
Version: DTC 1.4.1-gbd1c3aca-dirty
```

**Comment by smlng** [comment]
though your `dtc` version is different

**Comment by smlng** [comment]
or was it just the missing `-@` that caused the error?

**Comment by florian-popup** [comment]
well so far of what I read was that some DTC version has been compiled without the -@ options (the one that is in the ubunto repo for example)

**Comment by smlng** [comment]
I personally use Raspbian for that matter, and haven't used Ubuntu on Raspberry Pi (yet). I'll close this one again.
