### ISSUE TITLE
RADVD config description proposes link-local address for ABRO

### ISSUE THREAD

**Issue by miri64** [RIOT-Makers/wpan-raspbian#9]
In https://github.com/RIOT-Makers/wpan-raspbian/wiki/Setup-native-6LoWPAN-router-using-Raspbian-and-RADVD#configure-6lr a link-local address is proposed for the ABRO. This can lead to a faulty network in a multihop scenario: This address is used e.g. for multihop duplicate address detection which sends the DAR to the address given in this field. If the border router is more than one hop away from the router issuing the DAR, it won't be able to deliver that DAR => DAD would fail.

**Comment by smlng** [comment]
mhm, I remember that I wanted to fix that - but haven't come around reading the RFC on that topic. So you would suggested to put a global (or ULA when testing) there, instead?

**Comment by miri64** [comment]
Yap.

**Comment by smlng** [comment]
fixed in wiki and file, close if you approve.

**Comment by smlng** [comment]
@miri64 IMHO this is fixed and can be closed, or not?

**Comment by miri64** [comment]
Yapp.
